name: Github Runners Example

on:
  push:
    branches:
    - main
  workflow_dispatch: 


jobs:
  job-1:    
    runs-on: self-hosted
    steps:
    - name: Creating a Folder
      run: |
            echo "Creating the folder"
            mkdir /home/ubuntu/fatima-self-hosted-folder-new
            echo "Checking current directory"
            pwd
            ls




# jobs:
#   job-1:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Creating a Folder
#       run: |
#             echo "${{secrets.SSH_KEY}}" >> key.pem
#             chmod 400 key.pem
#             echo "SSH into the server"
#             ssh -o StrictHostKeyChecking=no -i "key.pem" ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
#             echo "Creating the folder"
#             mkdir /home/ubuntu/fatima-folder
#             echo "Checking current directory"
#             pwd
#             ls
#             "

#             pwd
#             ls
           
      








#### ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/ssh/known_hosts
