name: Deployment

# on:
#   push:
#     branches:
#       - main


on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Print simple statement
        run : echo "A pull request has been created!"
