name: Deployment

# on:
#   push:
#     branches:
#       - main


# on:
#   pull_request:
#     branches:
#       - main

on:
  issues:
    types: [opened,closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Print simple statement
        run : echo "An issue has been opened / closed"
